django_project/app_1/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),  # Added new path. Takes a string as the "name"
    path("paulina", views.paulina, name="paulina")
]

django_project/app_2/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
]

django_project/app_3/urls.py
from django.urls import path

from . import views

app_name = "app_3"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app_1/", include("app_1.urls")),
    path("app_2/", include("app_2.urls")),
    path("app_3/", include("app_3.urls"))
]

django_project/app_3/models.py
from django.db import models

# Create your models here.

django_project/app_1/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, "app_1/index.html")


def paulina(request):
    return HttpResponse("Hello, Paulina!")


def greet(request, name):
    return render(request, "app_1/greet.html", {
        "name": name.capitalize()  
    })

django_project/app_2/views.py
import datetime
from django.shortcuts import render


# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "app_2/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

django_project/app_3/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")


def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "app_3/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("app_3:index"))
        else:
            return render(request, "app_3/add.html", {
                "form": form
            })

    return render(request, "app_3/add.html", {
        "form": NewTaskForm()
    })

django_project/app_1/templates/app_1/greet.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
  </head>

  <body>
    <h1>Hello, {{ name }}!</h1>
  </body>

</html>

django_project/app_1/templates/app_1/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
  </head>

  <body>
    <h1>Hello, world!</h1>
  </body>

</html>

django_project/app_2/templates/app_2/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's?</title>
    <link href="{% static 'app_2/styles.css' %}" rel="stylesheet">
  </head>

  <body>
    {% if newyear%}
      <h1>YES</h1>
    {% else %}
      <h1>NO</h1>
    {% endif %}
  </body>

</html>

django_project/app_3/templates/app_3/add.html
{% extends "app_3/layout.html" %}

{% block body %}
      <h1>Add Task</h1>
      <form action="{% url 'app_3:add' %}" method="post">
        {% csrf_token%}
        {{ form }}
          <input type="submit">
      </form>
      <a href="{% url 'app_3:index' %}">Index</a>
{% endblock %}

django_project/app_3/templates/app_3/index.html
{% extends "app_3/layout.html" %}

{% block body %}
    <ul>
      <h1>Tasks</h1>
      {% for task in tasks %}
        <li>{{ task }}</li>
        {% empty %}
          <li>No tasks.</li>
      {% endfor %}
    </ul>
    <a href="{% url 'app_3:add' %}">Add a New Task</a>
{% endblock %}

django_project/app_3/templates/app_3/layout.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
  </head>

  <body>
    {% block body %}
    {% endblock %}
  </body>

</html>